### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by ALongLi** [xingangsun/react-redux-ie8#1]
process.stdout.clearLine is not a function

**Comment by xingangsun** [comment]
@ALongLi

**Comment by xingangsun** [comment]
@ALongLi My node version is 5.11.1, may be your version is too low.
[The reference solution](http://stackoverflow.com/questions/34570452/node-js-stdout-clearline-and-cursorto-functions)

**Comment by ALongLi** [comment]
my node version is  6.9.4

**Comment by xingangsun** [comment]
You can delete this line of code
